const GET_BOOKS = 'GET_BOOKS';
const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';
const REMOVE_BOOK_FROM_CART = 'REMOVE_BOOK_FROM_CART';

export {
    GET_BOOKS,
    ADD_BOOK_TO_CART,
    REMOVE_BOOK_FROM_CART
}
